### ISSUE TITLE
Do not hardcode version number in setup.py

### ISSUE THREAD

**Issue by uvilla** [hippylib/hippylib2muq#1]
Do not hardcode version numer in `setup.py`.

Instead, use the same construct that `hippylib` does to read the version number from `hippylib/version.py`.

Note: Also use `0.1.0` as version instead of `1.0.0`. This will tell user that the API of the code is still fluid.

**Comment by ktkimit** [comment]
I updated it accordingly. Thank you, @uvilla , for adding version.py!

**Comment by uvilla** [comment]
👍
