### ISSUE TITLE
More friendly documention

### ISSUE THREAD

**Issue by uvilla** [hippylib/hippylib2muq#2]
Please see how `hippylib` hippylib generate the documentation for a more user friendly webpage:

https://github.com/hippylib/hippylib/blob/master/doc/hippylib.rst

In particular:
1. Show the content of README.md and INSTALL.md in the documentation
2. It would be nice to have a static version of the notebook together with the documentation.

Also, documentation is now live at this address: https://hippylib.github.io/hippylib2muq/
It will be updated automatically everytime that you push to `gh-pages` branch.

**Comment by ktkimit** [comment]
I updated API documentation with a static version of the tutorial notebook.

**Comment by uvilla** [comment]
The documentation website looks great.

Can you also add instructions on how to generate the documentation in the INSTALL.md ?

Also, make sure to upload all files necessary to create the documentation.

**Comment by ktkimit** [comment]
Thank you, @uvilla ! No problem, I will do that.

**Comment by ktkimit** [comment]
I just pushed some updates including the instruction for locally generating the document.
