### ISSUE TITLE
Review installation instructions

### ISSUE THREAD

**Issue by uvilla** [hippylib/hippylib2muq#3]
I highly recommend to remove pip as a modality to install the software.

Since MUQ (and FEniCS) can not be pip installed, having a pip package is not that helpful.

In retrospective, it was an error to create `pip` packages for hippylib.

Also, please specify the dependecies versions for hippylib, muq, and fenics.

**Comment by ktkimit** [comment]
I removed the pip installation. I will update the installation guide when the conda version of muq is available. Many thanks!

**Comment by uvilla** [comment]
Looks good!
